font_family      JetBrainsMono Nerd Font
window_padding_width 10

#selection_foreground     #f8f8f2
#selection_background     #cc241d

#active_border_color      #ff5555
#inactive_border_color    #555555

#active_tab_foreground    #f8f8f2
#active_tab_background    #cc241d
#inactive_tab_foreground  #d0d0d0
#inactive_tab_background  #333333

#background               #000000
#foreground               #f0f0f0

background_opacity 0.7
cursor_blink_interval 0

include theme.conf
