# ============================================
# HYPRLAND MAIN CONFIGURATION FILE
# ============================================

# 1. TEMA (Deve essere assolutamente il primo per caricare le variabili)
source = ~/.config/hypr/theme.conf

# 2. MONITOR (Gestito dal tuo nwg-displays o manualmente)
source = ~/.config/hypr/monitors.conf

# 3. IMPOSTAZIONI DI SISTEMA E INPUT
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/input.conf

# 4. ASPETTO VISIVO E ANIMAZIONI
source = ~/.config/hypr/modules/look_and_feel.conf

# 5. PROGRAMMI IN AVVIO
source = ~/.config/hypr/modules/autostart.conf

# 6. REGOLE FINESTRE E KEYBINDINGS
source = ~/.config/hypr/modules/windowrules.conf
source = ~/.config/hypr/modules/keybindings.conf
