general {
    disable_loading_message = true
    hide_cursor = true
}

background {
    color = #000000
}
label {
    text = $TIME
    color = grey
    font_size = 64
    position = 0, -150
    halign = center
    valign = center
}

label {
    text = $USER
    color = grey
    font_size = 20
    position = 0, 50
    halign = center
    valign = center
}

input-field {
    size = 300, 50
    position = 0, 200
    halign = center
    valign = center

    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.3
    placeholder_text =

    outer_color = rgb(444444)
    inner_color = rgb(333333)
    font_color = rgb(ffffff)

    fade_on_empty = false
    check_color = rgb(ff0000)
}