wallpaper {
    monitor = eDP-1
    path = /home/matteo/.config/hypr/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-2
    path = /home/matteo/.config/hypr/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-9
    path = /home/matteo/.config/hypr/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/matteo/.config/hypr/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/matteo/.config/hypr/wallpaper.jpg
    fit_mode = cover
}