#################
### AUTOSTART ###
#################
exec-once = foot --server
exec-once = ~/.config/hypr/scripts/start_zen_bg.sh
exec-once = hyprpaper
exec-once = quickshell --path ~/.config/quickshell/shell.qml & $rog
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = nm-applet --indicator
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprsunset -t 5000
exec-once = ~/.config/hypr/scripts/switch_theme.sh nero

exec-once = cliphist list | tail -n +501 | cliphist delete
