#############
### INPUT ###
#############
input {
    kb_layout = it
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace
gesture = 4, horizontal, move
gesture = 3, up, close
gesture = 3, down, dispatcher, exec, hyprctl dispatch togglefloating; hyprctl dispatch resizeactive exact 800 600; hyprctl dispatch centerwindow
