#####################
### LOOK AND FEEL ###
#####################
general {
    gaps_in = $gaps_in
    gaps_out = $gaps_out
    border_size = $border_size
    col.active_border = $active_border
    col.inactive_border = $inactive_border
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = $rounding
    rounding_power = $rounding_power
    active_opacity = $active_opacity
    inactive_opacity = $inactive_opacity
    shadow {
        enabled = $shadow_enabled
        range = $shadow_range
        render_power = $shadow_render_power
        color = $shadow_color
    }
    blur {
        enabled = $blur_enabled
        size = $blur_size
        passes = $blur_passes
        vibrancy = $blur_vibrancy
    }
}

animations {
    enabled = false
    bezier = easeOutQuint,0.83, 0, 0.17, 1
    animation = windows, 1, 10, default, slide bottom
    animation = windowsOut, 1, 10, default, slide top
}

dwindle {
    # pseudotile = true # removed
    preserve_split = true
}

master {
    new_status = master
}

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    background_color = 0x000000
    animate_manual_resizes = true
    # vfr = true
    vrr = 1
}

#########################
### BEST BATTERY LIFE ###
#
#animations {
#enabled = false
#}
#decoration {
#rounding = 0
#shadow {
#enabled = false
#}
#blur {
#enabled = false
#}
#}
#
#
### MONITORS ###
################
xwayland {
  force_zero_scaling = true
}

#debug {
#  overlay = true
#  damage_blink = false
#}
#render {
#  direct_scanout = true
#}

cursor {
    no_hardware_cursors = false
    sync_gsettings_theme = true
    inactive_timeout = 5
}
