##############################
### WINDOWS AND WORKSPACES ###
##############################
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
workspace = 2, layoutopt:direction:right

windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]

windowrule = match:class blueberry.py, float on
windowrule = match:class blueberry.py, size 400 500
windowrule = match:class blueberry.py, move (monitor_w-410) 35

windowrule = match:class org.gnome.Calculator, float on
windowrule = match:class org.gnome.Calculator, size 400 500
windowrule = match:class org.gnome.Calculator, move (monitor_w-410) 95

windowrule = match:title ^(Apri file|Open File|Salva come|Save As|Sfoglia|Library)$, float on
windowrule = match:title ^(Apri file|Open File|Salva come|Save As|Sfoglia|Library)$, size 800 500
windowrule = match:title ^(Apri file|Open File|Salva come|Save As|Sfoglia|Library)$, center on

windowrule = match:class xdg-desktop-portal-gtk, float on
windowrule = match:class xdg-desktop-portal-gtk, size 900 600
windowrule = match:class xdg-desktop-portal-gtk, center on

# windowrule = match:class kitty, float on
# windowrule = match:class kitty, size 800 600
# windowrule = match:class kitty, center on

windowrule = match:class Spotify, float on
windowrule = match:class Spotify, size 800 600
windowrule = match:class Spotify, center on
windowrule = match:class Spotify, workspace special:magic silent
