$gaps_out = 10
$gaps_in = 5
$border_size = 1
$active_border = rgba(ff4500ee) rgba(00b2eeee) 45deg
$inactive_border = rgba(1a1b26aa)
$rounding = 10
$rounding_power = 4.0
$active_opacity = 1
$inactive_opacity = 1
$shadow_enabled = false
$shadow_range = 20
$shadow_render_power = 3
$shadow_color = rgba(00000066)
$blur_enabled = true
$blur_size = 8
$blur_passes = 3
$blur_vibrancy = 1696
$wallpaper = /home/matteo/.config/hypr/wallpaper/color.jpg

$bg_color = #1a1b26
$fg_color = #ffffff
$accent_color = #ff4500
