$gaps_out = 8
$gaps_in = 4
$border_size = 1
$active_border = rgba(2a7b85ee) rgba(081c24ee) 45deg
$inactive_border = rgba(142d33aa)
$rounding = 12
$rounding_power = 4.0
$active_opacity = 1
$inactive_opacity = 1
$shadow_enabled = false
$shadow_range = 10
$shadow_render_power = 3
$shadow_color = rgba(00000066)
$blur_enabled = true
$blur_size = 5
$blur_passes = 4
$blur_vibrancy = 1696
$wallpaper = /home/matteo/.config/hypr/wallpaper/dark_green.jpg

$accent_color = #2a7b85
$bg_color = #080d0f
$fg_color = #e1ecee
