$gaps_out = 10
$gaps_in = 5
$border_size = 1
$active_border = rgba(334155ee) rgba(0f172aee) 45deg
$inactive_border = rgba(1e293baa)
$rounding = 12
$rounding_power = 3.0
$active_opacity = 1
$inactive_opacity = 1
$shadow_enabled = false
$shadow_range = 20
$shadow_render_power = 4
$shadow_color = rgba(00000099)
$blur_enabled = true
$blur_size = 5
$blur_passes = 2
$blur_vibrancy = 1696
$wallpaper = /home/matteo/.config/hypr/wallpaper/dark_mountains.jpg

$bg_color = #0b101b
$fg_color = #f1f5f9
$accent_color = #94a3b8
