$gaps_out = 10
$gaps_in = 5
$border_size = 1
$active_border = rgba(527352ee) rgba(385238aa) 45deg
$inactive_border = rgba(0a0f0aaa)
$rounding = 10
$rounding_power = 4.0
$active_opacity = 1
$inactive_opacity = 1
$shadow_enabled = false
$shadow_range = 15
$shadow_render_power = 3
$shadow_color = rgba(1a1a1aee)
$blur_enabled = true
$blur_size = 6
$blur_passes = 2
$blur_vibrancy = 1696
$wallpaper = /home/matteo/.config/hypr/wallpaper/green.jpg

$bg_color = #0a0f0a
$fg_color = #e6e6e6
$accent_color = #527352
