$gaps_out = 5
$gaps_in = 3
$border_size = 1
$active_border = rgba(374151ff)
$inactive_border = rgba(111827ff)
$rounding = 10
$rounding_power = 2.0
$active_opacity = 1
$inactive_opacity = 1
$shadow_enabled = false
$shadow_range = 8
$shadow_render_power = 3
$shadow_color = rgba(00000033)
$blur_enabled = true
$blur_size = 4
$blur_passes = 4
$blur_vibrancy = 1696
$wallpaper = /home/matteo/.config/hypr/wallpaper/light_green.jpg

$accent_color = #a3e635
$bg_color = #111827
$fg_color = #f3f4f6
