$gaps_out = 10
$gaps_in = 5
$border_size = 1
$active_border = rgba(c65a47ee) rgba(4d6d80ee) 45deg
$inactive_border = rgba(1b2b34aa)
$rounding = 12
$rounding_power = 4.0
$active_opacity = 1
$inactive_opacity = 1
$shadow_enabled = false
$shadow_range = 15
$shadow_render_power = 3
$shadow_color = rgba(1a1a1aee)
$blur_enabled = true
$blur_size = 10
$blur_passes = 3
$blur_vibrancy = 1696
$wallpaper = /home/matteo/.config/hypr/wallpaper/line.jpg

$bg_color = #1b2b34
$fg_color = #e5d1c5
$accent_color = #c65a47
