$gaps_out = 10
$gaps_in = 5
$border_size = 1
$active_border = rgba(64748bee) rgba(94a3b8ee) 45deg
$inactive_border = rgba(334155aa)
$rounding = 10
$rounding_power = 4.0
$active_opacity = 1
$inactive_opacity = 1
$shadow_enabled = false
$shadow_range = 15
$shadow_render_power = 3
$shadow_color = rgba(1a1a1aee)
$blur_enabled = true
$blur_size = 4
$blur_passes = 2
$blur_vibrancy = 1696
$wallpaper = /home/matteo/.config/hypr/wallpaper/mountains.jpg

$bg_color = #1a1814
$fg_color = #e8e9e1
$accent_color = #7c907a
