$gaps_out = 15
$gaps_in = 5
$border_size = 1
$active_border = rgba(ff4b4bee) rgba(880808ee) 45deg
$inactive_border = rgba(280000aa)
$rounding = 8
$rounding_power = 2.0
$active_opacity = 1
$inactive_opacity = 1
$shadow_enabled = false
$shadow_range = 20
$shadow_render_power = 4
$shadow_color = rgba(ff000033)
$blur_enabled = true
$blur_size = 3
$blur_passes = 1
$blur_vibrancy = 3000
$wallpaper = /home/matteo/.config/hypr/wallpaper/red.jpg

$accent_color = #ff4b4b
$bg_color = #1a0505
$fg_color = #fee2e2
