$gaps_out = 0
$gaps_in = 5
$border_size = 1

$active_border = rgb(3a4d3a)
$inactive_border = rgba(1a231a55)

$rounding = 0
$rounding_power = 0
$active_opacity = 1
$inactive_opacity = 1

$shadow_enabled = false
$shadow_range = 4
$shadow_render_power = 3
$shadow_color = rgba(1a1a1aee)

$blur_enabled = false
$blur_size = 3
$blur_passes = 1
$blur_vibrancy = 0.1696

$wallpaper = /home/matteo/.config/hypr/wallpaper/simple_green.jpg

$accent_color = #a6e22e

$bg_color = #141b14
$fg_color = #cbd5cb
$tofi_selection = #a6e22e
