$gaps_out = 10
$gaps_in = 5
$border_size = 1
$active_border = rgba(ff9a8bee) rgba(8b9cffee) 45deg
$inactive_border = rgba(a2a6ccaa)
$rounding = 12
$rounding_power = 4.0
$active_opacity = 1
$inactive_opacity = 1
$shadow_enabled = false
$shadow_range = 15
$shadow_render_power = 3
$shadow_color = rgba(1a1a1aee)
$blur_enabled = true
$blur_size = 10
$blur_passes = 4
$blur_vibrancy = 1696
$wallpaper = /home/matteo/.config/hypr/wallpaper/soft_color.jpg

$bg_color = #2b304d
$fg_color = #fdf0ed
$accent_color = #ff9a8b
