$gaps_out = 10
$gaps_in = 5
$border_size = 1
$active_border = rgba(e65c34ee) rgba(f2a65aee) 45deg
$inactive_border = rgba(3d2b24aa)
$rounding = 12
$rounding_power = 4.0
$active_opacity = 1
$inactive_opacity = 1
$shadow_enabled = false
$shadow_range = 15
$shadow_render_power = 3
$shadow_color = rgba(1a1a1aee)
$blur_enabled = true
$blur_size = 4
$blur_passes = 3
$blur_vibrancy = 1696
$wallpaper = /home/matteo/.config/hypr/wallpaper/yellow.jpg

$bg_color = #261b17
$fg_color = #fceae0
$accent_color = #e65c34
